### ISSUE TITLE
AUR package for arch based distros

### ISSUE THREAD

**Issue by manorit2001** [Fushko/gummy#1]
I can see that there is another project of yours [gammy](https://github.com/Fushko/gammy) which was being developed from a long time. I just wanted to know how far is this project from reaching the functionalities and robustness of gammy.

**Comment by Fushko** [comment]
It's already more robust and has more functionalities than gammy. It's got multi-monitor and (initial) backlight support, uses XCB instead of XLib for gamma control which is faster, and also has an important optimization which avoids unnecessary system calls with gamma control. And of course CLI (which could easily turn into an API for a graphical interface in the future). The codebase is better and cleaner in every way, even in this early state.

**Comment by manorit2001** [comment]
Could you release an AUR package for it?

**Comment by Fushko** [comment]
I would like to. I'm actually thinking of switching to Artix at some point.

**Comment by mi544** [comment]
I got the package into the AUR. Please find it here: <https://aur.archlinux.org/packages/gummy-git/>
@Fushko @manorit2001

**Comment by Fushko** [comment]
Thanks @mi544. Does it pull from the release tags or master? Master is not stable.

**Comment by mi544** [comment]
@Fushko
Yeah, the `-git` builds against latest master commit, being `-git`, which is a common practice in AUR. I can see that version just broke on me after buildning. Will create a version based build in a few.

**Comment by mi544** [comment]
@Fushko 
Created an AUR package that pulls the repo with `#tag=0.1` and builds against that, tested and everything seems to be functioning well. Please let me know if there's any issues with installing/building/running any of the packages.

As such, there's 2 gummy packages in the AUR right now:  
- <https://aur.archlinux.org/packages/gummy/> - pulls down the repo by the release tag and builds against that (stable)
- <https://aur.archlinux.org/packages/gummy-git/> - pulls down the repo and builds against the latest commit in master (unstable, bleeding-edge)

**Comment by Fushko** [comment]
Added to README. Thanks!
