### ISSUE TITLE
Will there be a windows version?

### ISSUE THREAD

**Issue by herbzhao** [Fushko/gummy#2]
Gammy was always one of the first software i install when i get onto a new computer.. but I suffer from no control of multi-monitors.. 
I see the new Gummy is already supporting that but only on Linux. Would you consider porting it to windows or the code is infeasible to be ported?

**Comment by Fushko** [comment]
No. I haven't used windows in years and I don't plan to.

**Comment by XenSide** [comment]
Would there be any slight chance that you could make a build instruction for Windows in the Gammy repo?
 I'm unfortunately not very versed in the world of QT and even trying for an entire evening I wasn't able to understand. 

I made some changes to a fork already (making the slider value a percentage relative to the actual slider range instead of clamping) but I'm literally clueless on how to build it lol

**Comment by Fushko** [comment]
I didn't have a clue at the time either, I just downloaded QT Creator and let it do its thing.

**Comment by Boszacta-Emil** [comment]
this seems like a separate project, maybe someone could make a gwmmy program, this would require proper testing and utilization of windows apis, which this project does not have the mass for.
